pipeline {
    agent any
    tools {
        nodejs 'nodejs'
    }
    environment {
        containerRegistry = "f90mora/devops-test"
        GITHUB_REPO= "https://github.com/fer9003/devsu-devops-test.git"
        DATABASE_NAME = credentials('db_name')
        DATABASE_USER = credentials('db_user')
        DATABASE_PASSWORD = credentials('db_pass')
        AWS_DEFAULT_REGION = 'us-east-2' 
        AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
    }
stages {
    stage('Github Clone on JenkinsServer') {
        steps {
            echo "Cloning Project from Github"
            checkout scmGit(
                branches: [[name: '*/master']],
                extensions: [],
                userRemoteConfigs: [[url: GITHUB_REPO ]]
            )
        }
    }

    stage ('Github Clone on JenkinsNode') {
        agent {label 'local'}
        steps {
            checkout scmGit(branches: [[name: '*/master']],
            extensions: [], 
            userRemoteConfigs: [[url: GITHUB_REPO ]])
        }
    }

    stage('Unit Test') {
        steps {
            sh """
            cd microservice
            npm install && npm test
            """
        }
    }

    stage('Static Code Analysis') {
        environment {
            scannerHome = tool 'sonarqube-scanner' /* global-config */
        }

            steps {
                withSonarQubeEnv('sonarqube') { /* configuration server */
                    sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=microservice \
                    -Dsonar.projectName=microservice \
                    -Dsonar.projectVersion=1.0 \
                    -Dsonar.sources=microservice/ '''
                }
            }
        }

    stage('Container Image Scan') {
       agent {label 'local'} 
       steps {
            parallel (
                "Container Image Scan": {
                    sh '''
                       cd microservice/
                        bash trivy-container-scan.sh
                    '''
                },
                "OPA Dockerfile": {
                    sh '''
                        cd microservice/
                        docker run --rm -v $(pwd):/project openpolicyagent/conftest test --policy opa-docker-sec.rego Dockerfile 
                    '''
                }
            )
        }
    }

    stage('Docker Build and Push') {
        when {
            expression {
                BRANCH_NAME == "master"
            }
        }
        steps {
            withDockerRegistry([credentialsId: "dockerhub", url:""]) {
                sh """
                cd microservice/
                docker build -t $containerRegistry:""$GIT_COMMIT"" .
                docker push $containerRegistry:""$GIT_COMMIT""
                """
            }
        }
    }

     stage ('Deploy to Dev K8s') {
            when {
                expression {
                    BRANCH_NAME == "master"
                }
            }
            agent {label 'local'}
            steps {
                script {
                    withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONF')]) {
                        sh """
                        export KUBECONFIG=\${KUBECONF}
                        export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
                        export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
                        export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
                        cd microservice/
                        aws eks list-clusters
                        if kubectl get namespace development > /dev/null 2>&1; then
                            echo "El namespace ya existe"
                        else
                            kubectl create namespace development
                        fi
                        helm upgrade --install --force devopstest dev-helmchart --set nodeimage=${containerRegistry}:""$GIT_COMMIT"" --namespace development
                        """
                    }
                    
                }
            }
        }
    
    stage('Integration Test') {
        steps {
            echo "En esta fase se recomienda agregar test automatizados de integración, carga y rendimiento"
        }
    }

     stage('Promote to Production') {
        steps {
          timeout(time: 2, unit: 'DAYS') {
            input 'Aprueba el paso a ambiente de producción ?'
          }
        }
      }

    stage ('Deploy to Production K8s') {
        when {
            expression {
                BRANCH_NAME == "master"
            }
        }
        agent {label 'local'}
        steps {
            script {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONF')]) {
                    sh """
                        export KUBECONFIG=\${KUBECONF}
                        export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
                        export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
                        export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
                        cd microservice/
                        aws eks list-clusters
                        if kubectl get namespace production > /dev/null 2>&1; then
                            echo "El namespace ya existe"
                        else
                            kubectl create namespace production
                        fi
                        helm upgrade --install --force devopsprod helmchart --set nodeimage=${containerRegistry}:""$GIT_COMMIT"" --namespace production
                    """
                    }
                    
                }
            }
        }


}
}